### ISSUE TITLE
Cannot reconnect without full Home Assistant restart

### ISSUE THREAD

**Issue by DIYtechie** [raulgbcr/lednetwf_ble#1]
First of all THANK YOU for making this integration. Have been searching for this for months! It was easy to set up and auto-discover worked well with my lamp. Thanks!

My issue are

- if I lose power to my BLE receiver (ESP BT proxy), even for 30 seconds, I permanently lose connection to my lamp and have to restart Home Assistant to reconnect.

- I tried changing the timeout but this was not possible (“unknown error occurred”) and I’m not sure if that would help anyway?

- if I change brightness it will stop the multicoloured motion light and select a single color

**Comment by raulgbcr** [comment]
Hello! Thank you for using the integration!

Regarding your issues,

- For the ESP BT proxy, unfortunately I do not have any of these to test, and the integration relies heavily on bleak, which is a Linux library for interacting with BT devices and connecting/reconnecting, I really don't know if this works well with the BT proxy since I have no idea how the proxy works. You could try checking your logs to see if something weird pops up, should generate a log every time the device disconnect unexpectedly, which i have seen happening some times, maybe because I'm completely ignoring the counters/checksums of the protocol (they don't seem necessary at all) and the controller gives up after some time, but it should reconnect automatically when you send a command to it, that doesn't seem to be your issue thou. All works well here with a USB BT adapter connected to Home Assistant

- The timeout should be 120 seconds by default, I have no idea about how that error can pop, i can change it without problem, maybe check your logs to see if you see something strange regarding this

- The brightness right now sends a color temp or hsv packet depending what is the last mode the light was put in, unfortunately the integration doesn't support effects at the moment so that packet just resets your light to the color with the desired brightness, right now this is expected. Effects have their own brightness value in their unique packet, so they should be possible to implement at some point. Also if you change something with the remote and then make a change from Home Assistant it will just overwrite it, since no decoding of the current status, it isn't implemented at the moment

I don't have much free time right now and don't know when i will be able to tinker with the effects and the decoding, but feel free to PR changes if you wanna help in that regard!

**Comment by raulgbcr** [comment]
I have been playing a little with a couple of esphome bt proxies. There isn't much documentation or information online about how those work, so unfortunatelly the support for them its pretty much none. If anyone knows more about the proxies and want to adapt anything here for them to work go ahead.
