### ISSUE TITLE
Set R-G-B channel order

### ISSUE THREAD

**Issue by OctarineLobster** [raulgbcr/lednetwf_ble#16]
Would it be possible to add an option to switch the Blue and Green channels?

Great add on! Thanks.

**Comment by 8none1** [comment]
I worked out the colour handling protocol today and documented it here:  https://github.com/8none1/zengge_lednetwf?tab=readme-ov-file#rgb-colour-handling

The problem comes with how to expose this information in Home Assistant.  

At the moment we only use the standard `LIGHT` UI which doesn't have provision for any kind of drop downs.

I'd like to work out how to add this, but it might take some time. 

In the meantime, you should be able to configure your lights using the phone app and that setting /should/ stick.

**Comment by raulgbcr** [comment]
So I guess there are 2 approachs here. Either we handle this "internally" and swap the channels before sending the HSV value, or somehow send that packet to change the handling on the device itself. Configs could be added in the configuration section for the integration, but not sure if we could send a packet from there to update the setting in the device

**Comment by 8none1** [comment]
Oh!  I'm an idiot.  There is a configuration screen...
![image](https://github.com/raulgbcr/lednetwf_ble/assets/6552931/27c4d6ab-6d08-4f66-b7ce-5577bf744c15)

We might be able to add it to that?

**Comment by 8none1** [comment]
Hmm.  Problem... 

If we accept user input to change the colour ordering via that packet then we MUST also know the numbers LEDs in the strip, the number of segments and the LED type because all of those are set in the same packet. 

If we guess those then we risk breaking an already working set up.

There must be a way of reading the current configuration from the device.

I'll endevour to take a look tomorrow.

**Comment by raulgbcr** [comment]
Honestly, if changing it on the original app persist it I wouldn't really risk it here.

**Comment by 8none1** [comment]
Fair point.  +1

**Comment by 8none1** [comment]
This is now supported in the latest release.
